import { Link } from "@tanstack/react-router";
import { Activity, ArrowRight, HeartPulse, Search } from "lucide-react";
import type { Disease } from "@/data/diseases";

export function Header() {
  return <header className="sticky top-0 z-20 border-b bg-background/95 backdrop-blur-sm"><nav aria-label="Navigation principale" className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-2 px-5 py-3"><Link to="/" className="flex min-h-11 items-center gap-2 font-display text-xl font-semibold"><HeartPulse className="size-6 text-primary"/>Santé.Afrique</Link><div className="flex items-center gap-1 text-sm font-semibold sm:gap-3"><Link to="/recherche" activeProps={{className:"text-primary underline underline-offset-4"}} className="flex min-h-11 items-center gap-1 px-2 hover:text-primary"><Search className="size-4"/>Chercher</Link><Link to="/maladies" activeProps={{className:"text-primary underline underline-offset-4"}} className="flex min-h-11 items-center px-2 hover:text-primary">Maladies</Link><Link to="/pays" activeProps={{className:"text-primary underline underline-offset-4"}} className="flex min-h-11 items-center px-2 hover:text-primary">Pays</Link></div></nav></header>;
}
export function Footer() { return <footer className="border-t bg-secondary"><div className="mx-auto grid max-w-6xl gap-6 px-5 py-10 text-sm text-muted-foreground md:grid-cols-2"><p><strong className="text-foreground">Santé.Afrique</strong><br/>Information éducative uniquement. En cas de doute, consultez un professionnel de santé.</p><nav aria-label="Informations légales" className="flex flex-wrap items-center gap-5 md:justify-end"><Link className="hover:text-primary" to="/politique-confidentialite">Confidentialité</Link><Link className="hover:text-primary" to="/conditions-utilisation">Conditions d’utilisation</Link></nav></div></footer>; }
export function DiseaseCard({ d }: { d: Disease }) { return <Link to="/maladies/$slug" params={{slug:d.slug}} className="group block min-h-56 bg-card p-6 transition-colors duration-200 hover:bg-secondary focus-visible:outline-2 focus-visible:outline-primary"><Activity className="size-7 text-primary"/><h3 className="mt-5 font-display text-2xl font-semibold">{d.name}</h3><p className="mt-3 text-base leading-6 text-muted-foreground">{d.summary}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-primary">Lire la fiche <ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></span></Link>; }
